# Generated by Django 5.1.4 on 2025-01-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                ("preferences", models.TextField(max_length=250)),
            ],
        ),
    ]
